### ISSUE TITLE
A little confused about the license

### ISSUE THREAD

**Issue by kozross** [AbsInt/CompCert#140]
The LICENSE file states that a bunch of stuff for this compiler is under a non-commercial, education-only licence. Then, later, it says that those same files can be used under the GPL. This is a little confusing, and I would like clarification.

**Comment by xavierleroy** [comment]
It's called dual licensing: https://en.wikipedia.org/wiki/Multi-licensing

The files in question are, from a formal verification standpoint, the interface to CompCert.  They are licensed under the non-commercial license (NCL) so that they can be used together with the rest of CompCert (the implementation of the compiler, so to speak), which is NCL-only.

Additionally, the interface files in question are also licensed under the GPL so that they can be used in other, open-source projects such as VST (http://vst.cs.princeton.edu/) that connect with CompCert.

Note that GPL and NCL are incompatible.

**Comment by giltho** [comment]
Hi,

I'm also a tiny bit lost in the license file. I've forked CompCert and built a pre-extracted version of part of the modules : https://github.com/giltho/CompCert.
The changes are minor and described in https://github.com/giltho/CompCert/tree/master/CHANGES.md

My group is using CompCert (and more precisely C->Csharpminor compiler + Memory OCaml module) for a project. Our code does not include CompCert directly, but my fork of CompCert is "imported" using the following in the esy.json: 
```json
{
   "dependencies": {
      "compcert": "giltho/CompCert#commitHash"
   }
}
```
You can see it as an opam pin of a specific commit hash.


We'd like to open source our code under BSD license, is it conflicting with CompCert's license ?

PS: I didn't want to open a new issue for license questions, so that one can easily find answers about license by looking at this one issue.
