### ISSUE TITLE
ccomp seems to go on for a long while... had to kill it

### ISSUE THREAD

**Issue by msprotz** [AbsInt/CompCert#177]
Hello,

I need help figuring things out. If you unzip the attached file then `cd ccomp`, then the following command does not terminate.

```
jonathan@chartreuse:/tmp/ccomp $ ccomp -g -fstruct-passing -I. -c Curve25519.c -o Curve25519.o
```

[ccomp.zip](https://github.com/AbsInt/CompCert/files/839148/ccomp.zip)

I left it running for a couple minutes, then had to kill the process. It's using 100% of my CPU. This is on OSX, using the `ccomp` from Homebrew, version 3.0.

I do understand that all bets are off with `-fstruct-passing`, but I'm still surprised that this should send compcert off the rails. The code does compile using other off-the-shelf compilers and `clang` or `gcc` do not seem to exhibit any strange behavior when compiling this file.

Thanks,

Jonathan

**Comment by m-schmidt** [comment]
I cannot reproduce this. Using the current trunk version (that is v3.0.1) it takes about 22 seconds to compile this file on my machine (iMac, 3.3GHz, Sierra). Memory usage is a little more than 210MB.

**Comment by msprotz** [comment]
Alright, my bad:

```
real	2m55.068s
user	2m52.201s
```

I'm recompiling compcert from trunk to see if the newer version improves the time it takes to compile this file.

**Comment by msprotz** [comment]
Indeed, on trunk:

```
real	0m21.961s
user	0m21.733s
sys	0m0.191s
```

Thanks for the suggestion... I'll switch to the trunk version of compcert.

Best,

Jonathan

**Comment by m-schmidt** [comment]
Thanks for the feedback.

**Comment by xavierleroy** [comment]
I haven't the slightest idea of what cuases such a dramatic change in compilation times...  Which version of CompCert exhibits the 2m55 compilation time?  And, concerning the trunk version, is it configured for x86_32 or x86_64?

**Comment by m-schmidt** [comment]
In my case it was 64bit. The other version is from homebrew (and therefore I assume also 64bit). I will test it tomorrow.

**Comment by msprotz** [comment]
Yes, the 2m55 compilation is with Compcert 3.0 from Homebrew, which I assume is configured for x86_64 (but I'll double-check). My manually-compiled compcert used `./configure x86_64-macosx`.

**Comment by msprotz** [comment]
CompCert 3.0 / `x86_64` also does not exhibit the problem. It seems specific to the 32-bit version of CompCert.

```
real	0m22.284s
user	0m22.041s
```

(after recompiling 3.0 to use x86_32).

**Comment by xavierleroy** [comment]
All right, I could reproduce the timing difference with trunk.  As I suspected, it's register allocation that takes a lot of time in 32 bit mode, on the order of 30 times more than in 64 bit mode.  There are several reasons:
* Half of the registers are available in 32-bit mode, so it's significantly harder to find a register allocation than in 64-bit mode.
* The intermediate RTL code is 2.7 times bigger in 32-bit mode than in 64-bit mode, because 64-bit integer operations are expanded into multiple 32-bit integer operations, and because of `-fstruct-passing` (see below).  
As a consequence of the bigger RTL code, several back-end passes also take more time in 32 bit mode, but it's not as spectacular as register allocation.

Concerning `-fstruct-passing`: in 32 bit mode, CompCert uses the ABI standard calling conventions.  This comes at a cost in terms of complexity of intermediate code, i.e. any `FStar_UInt128_t` argument that is passed by value is actually 4 arguments of type `int32_t`.  In 64 bit mode, the ABI is so complicated that CompCert doesn't implement it yet and uses its by-default convention, passing structs by reference and copy in the callee.  This generates simpler code that CompCert can optimize better.  But it is not ABI compliant and will crash horribly when linking codes compiled by CompCert and by another compiler.

The moral of the story is that you should really stop passing structs by value if you want to benefit from CompCert: either the implementation is ABI-compliant but not verified (and somewhat hackish), or it is verified but not interoperable with other compilers.

**Comment by msprotz** [comment]
Thanks Xavier. We are in the process of getting away from by-value structs, but they sure are convenient, as they incur no proof obligations at the F\* level: by virtue of being values, they are always live. Tahina wrote a library of by-reference, mutable, nested (flat) structures, so we plan to port our code to the new formalization soon.

In this specific case, though, the cryptographic algorithm relies for performance on 128-bit integers, which are implemented natively by GCC and Clang, which makes our life easier. As far as I could tell, the `__128_t` type is not defined in CompCert, so we roll-out our own implementation using a pair of 64-bit integers, hence the issue.

Is primitive support for 128-bit integers on the radar, by any chance?

**Comment by msprotz** [comment]
Correct -- I was never intending to generate 32-bit code in the first place, I just got bitten by the default for Homebrew's packaged version of CompCert. I was just commenting on the "don't use structs by value if you want actual soundness guarantees" argument :).

**Comment by xavierleroy** [comment]
Yes, CompCert is not as feature-rich as GCC, and no, support for `int128_t` is not on the short-term agenda.  Although it could reuse a lot of code already present to emulate 64-bit integers on 32-bit platforms, so this is perhaps something to keep in mind.  Note that MSVC doesn't support `int128_t` either :-)   

It is true that structs passed by value are easier to reason about: seL4 uses a lot of them, for similar reasons.  From a compiler performance standpoint, they are hit-or-miss: either they go away after inlining and then it's bliss, or they stay and then the bizarre ABIs around make by-value passing as expensive or more expensive than pass-by-reference.
