### ISSUE TITLE
possible error

### ISSUE THREAD

**Issue by vzaliva** [AbsInt/CompCert#186]
In module Ctyping in definition `type_conditional` when combining two identical pointers with alignment attributes present, the alignment will be lost.

I am have not checked C language spec if it is the expected behavior, but I have a suspicion that it is a bug.

**Comment by bschommer** [comment]
It is the expected behavior, `type_conditional`  is used for the `conditional operator` and the C standard (both C99 and C11) state that:

> If both the second and third operands are pointers or one is a null pointer constant and the
other is a pointer, the result type is a pointer to a type qualified with all the type qualifiers
of the types referenced by both operands.

See §6.5.15 as reference.
