### ISSUE TITLE
_Alignas in typedef

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#197]
CompCert 2.7's treatment of _Alignas is different from (more liberal than) the C11 standard.  I strongly encourage you _not to change_ this, and even to **document that you support this more liberal interpretation**   (in Section 6 of the CompCert reference manual).

Why I like this:  It allows me to use _Alignas to implement a "fake attribute", useful in the Verifiable C type system for Clight.

What the C11 standard says: "An alignment attribute shall not be specified in a declaration of a typedef, or a bit-field, or a function, or a parameter, or an object declared with the register storage-class specifier."  (I refer to the draft standard, http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf, page 127).

What CompCert does:   permits alignment attributes in typedefs and function parameters, etc.

Why I want a new attribute:
The type system for Verifiable C (in VST) is exactly Ctypes.v from compcert/cfrontend.  In Verifiable C we interpret the (Tint _ _ noattr) type more strictly than CompCert C, that is, a variable of type (Tint _ _ noattr) cannot contain (Vptr _ _) values; and a variable of type (Tpointer _ _) cannot contain Vint values.  This is compatible, in the sense that every program we verify correct, is a legal CompCert C program  (actually Clight2).  It is desirable for Verifiable C, as it gives stronger assertions about (initialized) local variables and fields of integer or pointer type.

What is my problem:  The C language (and CompCert C) permits casting a Vptr value to the int type, storing in an integer variable, then (later) casting back to a pointer type.  At present, in Verifiable C, we cannot reason about such programs.  If we had (as another constructor in Ctypes.type) a "Tint_or_ptr" type, then we could distinguish these cases easily, and get the best of both worlds.  But I imagine you do not want to add another constructor to Ctypes.type, and another attribute to the source language syntax.

Therefore I propose to use the following hack in Verifiable C:  The type 
Tpointer t {| attr_volatile :=false; attr_alignas := Some 2 |}
shall mean, "Either a pointer or an integer".   We will make a small modification to the Verifiable C type-checker to act differently in this case.

This should make no difference to CompCert, and requires no changes at all in CompCert (except change your documentation to indicate that, unlike in standard C,  _Alignas can be attached to typedefs).

**Comment by andrew-appel** [comment]
The following may also be relevant, it's from the same standards document linked above.  As an alternative to the "expclitly aligned  Tpointer" hack, perhaps CompCert could support the C-standard "intptr_t" type, distinct from Tint and Tpointer.

**7.20.1.4 Integer types capable of holding object pointers**
1 The following type designates a signed integer type with the property that any valid pointer to void can be converted to this type, then converted back to pointer to void, and the result will compare equal to the original pointer:
`intptr_t`
The following type designates an unsigned integer type with the property that any valid pointer to void can be converted to this type, then converted back to pointer to void, and the result will compare equal to the original pointer:
`uintptr_t`
These types are optional.

**Comment by jeehoonkang** [comment]
As far as I understand the Standard, `uintptr_t` is an integral type, and once a pointer is casted to `uintptr_t`, it should be an integer.  At first, the purpose of pointer-to-integer casting is using a pointer as an integer, as in (1) tagging a pointer (e.g. 0x4001, which is 0x4000 tagged with 1), or (2) using a pointer as a key to a hash table.  For that reason, I hope a variable of type `uintptr_t` does not contain a pointer value in the future versions of CompCert.

**Comment by xavierleroy** [comment]
You're correct that in C11, `_Alignas` is attached to variable and struct/union members, while in CompCert it is attached to any type and therefore can be part of a typedef or of a pointer type, for example, just like the `const` and `volatile` modifiers.

There are some reasons, although they are not very strong: 1- it simplifies the CompCert C and Clight ASTs, by handling `_Alignas` just like `const` and `volatile`; 2- it is closer to what GCC does with the `aligned` attribute, which can be attached to typedefs as well.

Again I think this is an innocuous and potentially useful extension to C11, so why not support it? and even mention it in the manual, indeed?

The usage outlined by @andrew-appel is kind of the poor man's custom attribute in Clight: if Clight types were to support GCC-style arbitrary custom attributes, you'd use one of those (say, `int_or_ptr`) instead of the proposed encoding.  If the encoding works for you, it's great.  Arbitrary custom attributes in CompCert C and Clight can be considered, following what we do in `cparser/C.mli`, but it's a bit of a mess.

Concerning `uintptr_t` and `intptr_t`, these are just integer types `Tint` with the same size as a pointer.  We certainly don't want to represent them with a head constructor other than `Tint`, because for overloading arithmetic resolution they behave exactly like integer types.

**Comment by xavierleroy** [comment]
I closed the issue by accident, apologies for this.

**Comment by xavierleroy** [comment]
Added a mention to user's manual, will be in release 3.1.
