### ISSUE TITLE
_Alignas permitted less than natural alignment

### ISSUE THREAD

**Issue by andrew-appel** [AbsInt/CompCert#198]
The C11 language standard (at least in its draft version, I haven't looked at the paywall version), says
"The combined effect of all alignment attributes in a declaration shall not specify an
alignment that is less strict than the alignment that would otherwise be required for the
type of the object or member being declared."

http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf , page 127

Indeed, this program
     struct foo {   char c;   int _Alignas(1) i; } p;
     int main(void) { printf ("%d\n", (int)(&p.i) - (int) (&p));  return 0;   }

 does not compile with gcc 5.4.0:
 error: ‘_Alignas’ specifiers cannot reduce alignment of ‘i’

But it does compile with CompCert (any recent version, including specifically 3.0.1),
and the result is: it prints 1.  That is, it has aligned the "i" field on a not-multiple-of-4.

There are several possible solutions to this problem:

1.  Declare it "not a problem."     CompCert implements a refinement of the C standard,
and alignment at less than the natural alignment is permitted, contrary to the standard.
In this case, it should be documented in Section 6 of the CompCert reference manual,
so that users can rely on it.

2.  Detect this and print an error message, similar to gcc's.  No documentation in Section 6 necessary, because this is standard C semantics.

3.  Whenever there is an _Alignas directive at less than the natural alignment,
ignore it BEFORE THE TRANSLATION TO CLIGHT by setting attr_alignas to None.   Document this Section 6 of the CompCert reference manual.

4.  Change the Definition of align_attr to return the max of its two arguments,
rather than "use the first argument if Some, else the second".  This has the effect
of, "whenever there is an _Alignas directive at less than the natural alignment,
ignore it AFTER THE TRANSLATION TO CLIGHT."   Document this in section 6.

There is a difference between 3 and 4:  users who see the Clight program
(because they are verifying programs in VST) will see the difference.

**Comment by jeehoonkang** [comment]
I just want to note that #3 and #4 is incorrectly hyperlinked to the issue number 3 and 4, respectively.

**Comment by xavierleroy** [comment]
Yes, it is intentional that alignment can be reduced below the natural alignment, at least in the C internal representations (CompCert C, Clight, and the AST from `cparser/C.mli`).  This is used in particular to de-sugar "packed structs" (a popular C extension) into structs with fields having reduced alignment, just like in your `struct foo` example.  Also, GCC's `aligned` attribute supports reduced alignment as well, and in CompCert this attribute is treated like `_Alignas`.

It would still be possible to reject `_Alignas` with reduced alignment in C source programs, or to emit a warning.  Since the semantics of `_Alignas` is formally defined by CompCert, and since reduced-alignment `_Alignas` is no more dangerous than packed structs, I'm in favor of leaving it supported.  A warning controlled by a `-W` flag could be nice, however.

**Comment by andrew-appel** [comment]
As I suggested, it's very reasonable to continue supporting this.  But if so, I suggest documenting that it's on-purpose, not accidental.

**Comment by xavierleroy** [comment]
The behavior is already documented, see http://compcert.inria.fr/man/manual005.html paragraph 6.7.3:

> The alignment N given in the _Alignas(N) qualifier should normally be greater than or equal to the natural alignment of the modified type. For target platforms that support unaligned memory accesses (x86 and PowerPC, but not ARM), N can also be smaller than the natural alignment.
