### ISSUE TITLE
Cygwin 64bit support

### ISSUE THREAD

**Issue by mindbound** [AbsInt/CompCert#204]
Would it be possible to add this and, if so, are there plans to support it in the future?

**Comment by xavierleroy** [comment]
At the moment no support is planned because there is not enough demand and because some nontrivial technical work is needed.  (Cygwin 64 uses the Windows 64 ABI, which differs from the ELF x86-64 ABI already implemented in CompCert.)  

I'll keep this report open as a feature wish ("enhancement" tag).

**Comment by xavierleroy** [comment]
Support for Cygwin64 was added to the working CompCert sources in commit 26ddb902.  However, OCaml (one of the dependencies of CompCert and Coq) was broken under Cygwin64 for several releases, and was only recently fixed.  So, it's better to wait for the next release of OCaml, version 4.12, before trying to build CompCert under Cygwin64.
