### ISSUE TITLE
feature request: dump csharpminor

### ISSUE THREAD

**Issue by bollu** [AbsInt/CompCert#219]
It would be nice to have an option `-dcshm` that dumps out the `csharpminor`. There is both `-dclight` and `-dcminor`, so this is a natural extension.

Is a pull request towards this accepted? If so, I shall implement this.

**Comment by xavierleroy** [comment]
Sorry for the late reply.  There hasn't been much of a need for a C#minor dump so far.  Are you proposing it just for completeness or with a specific need in mind?  

At any rate, the main issue is to find a decent concrete syntax for C#minor.  For Clight it's easy because we try to print valid C as much as possible.  For Cminor the concrete syntax is a mess...

**Comment by bollu** [comment]
I wanted to read C#minor to understand the IR better.

Would it be reasonable to borrow Cminor's concrete syntax, Cminor and C#minor differ only mildly? That would at least be consistent with the rest of CompCert.

**Comment by bschommer** [comment]
I don't think there is much need for a dump of C#minor.
