### ISSUE TITLE
CompCert 3.2.0 and Coq 8.7.2

### ISSUE THREAD

**Issue by lastland** [AbsInt/CompCert#223]
The Makefile of CompCert 3.2.0 does not support Coq 8.7.2 (though it seems simply adding the 8.7.2 version number to the Makefile would make it work?). This causes problems for people who are using Coq 8.7.2 and CompCert 3.2.0, especially if they install CompCert using opam.

Is it possible to make a release of CompCert that supports Coq 8.7.2? Maybe 3.2.1?

**Comment by m-schmidt** [comment]
The current master already has proper support for Coq 8.7.2. If you want to stick with the release version, the configure script has an option `-ignore-coq-version` to skip the version test.

**Comment by lastland** [comment]
Hi @m-schmidt,

Thanks for the reply! I am aware that the current master has properly supported Coq 8.7.2. However, it would be more convenient if we can just install a compatible release from opam.

If the only thing we need to make the CompCert 3.2.0 release support Coq 8.7.2 is passing the `-ignore-coq-version` option, there is a simple fix: just add that option to the `configure` part in the `opam` file [here](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-compcert/coq-compcert.3.2.0/opam). Would you recommend that we do that?

**Comment by m-schmidt** [comment]
I would not recommend such a fix for the official Opam only for local versions (if this is possible).

**Comment by lastland** [comment]
Then do you think it is possible to make an opam release compatible with Coq 8.7.2?

**Comment by lastland** [comment]
Let me clarify a bit why I was proposing adding `-ignore-coq-version` option to `opam`. The reason is opam is already doing a checking for Coq's version (shown [here](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-compcert/coq-compcert.3.2.0/opam#L26)):
```
depends: [
  "coq"  {> "8.6.0" & < "8.8~"}
  "menhir" {>= "20160303"}
]
```
Checking it again in `Makefile` is redundant, unless there are some problems that cause Coq 8.7.2 to not work with CompCert 3.2.0.

**Comment by m-schmidt** [comment]
Maybe @xavierleroy can share his thoughts on this?

**Comment by xavierleroy** [comment]
@lastland is correct that OPAM performs version checks in addition to the checks done by CompCert's configure script.  Because of this, the use of `configure -ignore-coq-version` could be considered. 
 
However, the OPAM dependencies shown above are risky.  They assume that any future "8.7.x" version of Coq will not break CompCert.  In the past we've seen minor releases of Coq breaking CompCert.  That's why the configure script of CompCert accepts only versions of Coq that were tested to work with CompCert, and not "any future minor release of Coq".

Also the menhir dependency is wrong, it should be `>= 20161201`.

My preferred approach would be to make a new OPAM package for CompCert 3.2 that includes commit 3593971f9d5ec8fa95344e6d0cd25ec55642b365 as a patch, so that the configure script accepts 8.7.2.

My next preferred approach would be to use `configure -ignore-coq-version` but tighten the OPAM dependencies so that the only versions of Coq accepted are those that have been tested  to actually work.  It implies that a new version of the package must be published every time a new, compatible version of Coq is released, just like in the preferred approach above.

**Comment by bschommer** [comment]
The opam change is merged, although not the ideal version with the patch, but the version with `configure --ignore-coq-version`.
