### ISSUE TITLE
Packed structures with bit-fields

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#24]
In the following code:

```
#include <stdio.h>

typedef struct __attribute((packed)) {
  int a:8;
  int b:9;
} st;

int main() {
  printf("sizeof(st) = %u\n", sizeof(st));
  return 0;
}
```

CompCert (configured with `ia32-linux` and run with `-fbitfields -fpacked-structs`) produces code which prints `sizeof(st) = 4`, while GCC and Clang both print `sizeof(st) = 3`.

Is it possible to tell CompCert to make it pack this structure using only 3 bytes? If not, is this due to a compiler-specific implementation choice, or related to ABI issues?

**Comment by xavierleroy** [comment]
The layout of packed structs is not specified in the ELF ABI standards, so it's really up to the compiler.  In the case of CompCert, consecutive bitfields are first packed into an integer "carrier" field of type char, short, or int (the smallest that fits); then, the carrier field is laid out like any other integer field, with padding (by default) or without padding (if the "packed" attribute is given).  Since there are no integer type of size 3 bytes, the layout you're after cannot be achieved.

One workaround for this particular example is simply not to use a bitfield for "a":

typedef struct __attribute((packed)) {
 char a;
  int b:9;
} st;

I believe this achieves the expected layout.

More generally, the layout of bitfields is highly dependent on ABI and compiler.  It's best not to use them in portable code if a specific layout is to be implemented, instead using plain (arrays of) integers plus accessor functions.

**Comment by thranur** [comment]
Thank you very much for the information. Indeed, I should have rephrased my question as: "is there a clever hack to obtain the same result as GCC/LLVM?"

I was mostly considering interoperability between code compiled with GCC and code compiled with CompCert. But indeed it's very specific and I should not expect it to happen. Some tests with tcc indicated that GCC and LLVM agree mostly because of compatibility efforts in that direction, and not due to any merits of the C standard in that respect.

Thank you for the clarification and the suggestion.

**Comment by thranur** [comment]
Just a minor comment: the [user manual](http://compcert.inria.fr/man/manual006.html#attributes) states that

> `__packed__` is equivalent to `__attribute((packed))`

But in my tests, `__packed__` without arguments results in a syntax error, unless it is inside `__attribute`, as in `__attribute((__packed__))`. With at least one argument, `__packed__(...)` works as described. Perhaps this might be a better phrasing:

>   `__attribute((__packed__))` is equivalent to `__attribute((packed))`

**Comment by xavierleroy** [comment]
Thanks for reporting this.  Indeed, it used to be the case that "__packed__" alone was recognized by the parser.  However, it causes an LR conflict in the new, verified parser, so only "__packed()" is recognized now.  I'll update the user manual accordingly.
