### ISSUE TITLE
CompCert's FLT_EVAL_METHOD

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#27]
CompCert does not define a `FLT_EVAL_METHOD` macro, and due to the lack of `long double`, it normally would not fit into any of [C99's 3 defined methods](http://en.wikipedia.org/wiki/C99#IEEE.C2.A0754_floating_point_support); but according to the user manual, would it be safe to assume CompCert's behavior as equivalent to `FLT_EVAL_METHOD = 1` (intermediate expressions performed in `double` precision, as in K&R's C)? Or are there subtle differences which would prevent this?

**Comment by xavierleroy** [comment]
CompCert does not (currently) define FLT_EVAL_METHOD because (currently) it doesn't provide its own <float.h> standard header.  But I agree it would be good to define this macro one way or another.

CompCert can treat "long double" like "double" (option -flongdouble), which I believe is an acceptable choice according to C99.  The only reason it is not done by default is that it introduces ABI incompatibilities on x86 and PowerPC.

CompCert up to and including version 2.3 behaves like FLT_EVAL_METHOD=1, indeed.  (All intermediate results are computed with "double" precision.)

Starting with version 2.4, CompCert computes intermediate results of type "float" with "float" precision, as per FLT_EVAL_METHOD=0.  The earlier choice was easier to implement but was generating rather bad code for "float"-intensive numerical code.

**Comment by thranur** [comment]
Thank you for the clarification.

On a related note, it might be useful to update this part of section 5 of the user manual:
> All floating-point intermediate results are computed in double precision, even if all arguments are of type float.

**Comment by xavierleroy** [comment]
Oops, the manual need updating indeed.  Will do shortly.

The numbering of sections follows the numbering used in the ISO C99 standard, for easier reference.
