### ISSUE TITLE
memcpy built-in in interpreter mode

### ISSUE THREAD

**Issue by thranur** [AbsInt/CompCert#28]
I would just like some information about the status of the memcpy built-in on the interpreter.

It seems that most of the code to enable its use is already present on Interp.ml/Cexec.v.

In theory, I might follow the example of printf in `Interp.ml/do_external_function` to add it, but I wonder if there are subtle issues which would prevent it from working properly, or if it has not been done simply by lack of demand/to minimize the amount of code to be maintained.

**Comment by xavierleroy** [comment]
Thanks for bringing up this point.  Everything is there in Cexec.v to interpret __builtin_memcpy_aligned, and it seems to works fine with scalars or composites:

int a = 4;
int b;

int main(void)
{
  __builtin_memcpy_aligned(&b, &a, sizeof(a), _Alignof(a));
  return b;
}

This interprets correctly and return 4 as expected. 

However, something is wrong with arrays as arguments to __builtin_memcpy_aligned:

int a[4] = {1,2,3,4};
int b[4];

int main(void)
{
  __builtin_memcpy_aligned(b, a, sizeof(a), _Alignof(a));
  return b[3];
}

The reference interpreter reports an error here.  The bug is in C2C, which forgets to "decay" the array types of "a" and "b" into pointer types...  I'll fix this shortly.

Is this (the array example) the problematic case you observed?

**Comment by xavierleroy** [comment]
Issue with arrays fixed in commit [master e00261d].

**Comment by thranur** [comment]
I actually had a much simpler example in mind:

    int main(int c, char **v) {
        char x, y = 2;
        memcpy(&x, &y, 1);
        return 0;
    }

I wanted the interpreter to evaluate this program without reporting "undefined behavior" due to the fact that `memcpy` was not recognized by the interpreter (as described in the manual), but I was afraid it had not been done due to complex issues which I would not be able to solve, hence my question about it before committing myself to doing it.

Anyway, I'm glad it helped finding a real issue.

**Comment by xavierleroy** [comment]
Ah, I see.  CompCert has no specific knowledge about the memcpy function from <string.h>.  The __builtin_memcpy_aligned built-in function is not a replacement for memcpy, because it works only if the size and alignment are compile-time constants.  (In return, CompCert can generate rather good inlined code for it.)  

Off the top of my head, it is not obvious how to extend the reference interpreter to implement memcpy and similar basic library functions.
