### ISSUE TITLE
Is it possible to customize the pass order?

### ISSUE THREAD

**Issue by coffezhou** [AbsInt/CompCert#287]
Is it possible to customize the pass order?

**Comment by xavierleroy** [comment]
If you mean "are there command-line options to change the order of compilation passes", the answer is no.

If you mean "is it possible to patch CompCert's sources to change the order of compilation passes", the answer is yes, to some extent.  The optimization passes that go from RTL to RTL can be done in different orders.  Most other passes go from language A to language B with A different from B, and therefore cannot be reordered (because of types).
