### ISSUE TITLE
Typo on installation page

### ISSUE THREAD

**Issue by impression28** [AbsInt/CompCert#326]
The [installation page](http://compcert.inria.fr/man/manual002.html#install) says to execute `opam switch 4.07.1` but the comment says version 4.06.1. I suspect 4.06.1 is the correct one.

![Screenshot_2019-12-24 Installation instructions](https://user-images.githubusercontent.com/12220708/71419127-aa044d00-264c-11ea-89bb-6c8effd6dc07.png)

Additionally, I would suggest saying something to ensure the user gets the correct version of opam. My package manager installed an old version and it took me quite a while to figure out why I couldn't get the correct version of menhir. :)

**Comment by xavierleroy** [comment]
You're right there is a typo.  The recommended OCaml version is 4.07.1, but 4.06.1 should work too.  The manual was already fixed in preparation for the next release, but I'll try to fix the current version too.

Concerning OPAM, you're right that version 2 is required.  We'll add a note to this extent.
