### ISSUE TITLE
A memory overflow error?

### ISSUE THREAD

**Issue by QuXing9** [AbsInt/CompCert#332]
Hi,
When compiling the below testcase, compcert reports the Segmentation fault while other compilers like gcc and clang compiles successfully. I am confused why ccomp reports the segfault error. Looking forward to your reply.

TestCase:
#include<stdio.h>

#define S1 "aaaaaaaaaaaaaaaaaaaaa"
#define S2 S1 S1 S1 S1 S1 S1 S1 S1 S1 S1 S1
#define S3 S2 S2 S2 S2 S2 S2 S2 S2 S2 S2 S2
#define S4 S3 S3 S3 S3 S3 S3 S3 S3 S3 S3 S3
#define S5 S4 S4 S4 S4 S4 S4 S4 S4 S4 S4 S4
#define S6 S5 S5 S5 S5 S5 S5 S5 S5 S5 S5
#define S7 S6 S6 S6 S6 S6 S6 S6 S6 S6 S6 

void foo (void)
{
    printf (S7 "\n");
}

Compile command:
<install_dir>/ccomp -c testcast.c -o testcase.o

Compiler Version:
version 3.6

The OS is:
Linux version 4.15.0-65-generic

Output:
Segmentation fault

Expected output:
compile successfully

**Comment by bschommer** [comment]
The problem is the really large string constant that is the result of the macro `S7` and you are probably running out of memory during compilation. I tried it on my machine and killed the process after it consumed more than 10 GB Ram.

**Comment by QuXing9** [comment]
> The problem is the really large string constant that is the result of the macro `S7` and you are probably running out of memory during compilation. I tried it on my machine and killed the process after it consumed more than 10 GB Ram.

But I don't see a clear out-of-memory signal. My machine had 64GB of memory, and ccomp reported segfault when I had about 32GB of free memory. How can I confirm it's an out-of-memory error?

**Comment by xavierleroy** [comment]
The segfault could be due to a stack overflow or to excessive memory allocation.  The OCaml runtime system tries to raise exceptions for those two conditions, but stack overflow detection is not 100% reliable even on Linux, and if memory overcommit is enabled in the kernel, excessive memory allocation can return successfully from `malloc()` yet cause a segfault when accessing the allocated memory.

Generally speaking, this is not a CompCert problem.  It might be an OCaml bug, or just normal Linux behavior on overcommitted memory.

This said, I tried to reproduce the problem and could not.  First I got a `Stack_overflow` exception from OCaml.  After doing `ulimit -s unlimited`, `ccomp -c` succeeded, although it takes quite a while.  A lot of time is spend in the constant propagation pass.  `ccomp -c -O0` takes less time.  Remember that CompCert defaults to `-O1`, while gcc and clang default to `-O0`.

Finally, my personal advice concerning fuzzing (you seem to be into fuzzing based on your Github page): small random inputs find interesting bugs; huge inputs don't, they just cause testing to thrash the machine (by using up all memory) and take forever.  When fuzzing a compiler, put low limits on the stack space, the memory space, and the total compilation time.  Any test that exceeds these limits is not interesting.

**Comment by QuXing9** [comment]
> The segfault could be due to a stack overflow or to excessive memory allocation. The OCaml runtime system tries to raise exceptions for those two conditions, but stack overflow detection is not 100% reliable even on Linux, and if memory overcommit is enabled in the kernel, excessive memory allocation can return successfully from `malloc()` yet cause a segfault when accessing the allocated memory.
> 
> Generally speaking, this is not a CompCert problem. It might be an OCaml bug, or just normal Linux behavior on overcommitted memory.
> 
> This said, I tried to reproduce the problem and could not. First I got a `Stack_overflow` exception from OCaml. After doing `ulimit -s unlimited`, `ccomp -c` succeeded, although it takes quite a while. A lot of time is spend in the constant propagation pass. `ccomp -c -O0` takes less time. Remember that CompCert defaults to `-O1`, while gcc and clang default to `-O0`.
> 
> Finally, my personal advice concerning fuzzing (you seem to be into fuzzing based on your Github page): small random inputs find interesting bugs; huge inputs don't, they just cause testing to thrash the machine (by using up all memory) and take forever. When fuzzing a compiler, put low limits on the stack space, the memory space, and the total compilation time. Any test that exceeds these limits is not interesting.

Thanks for your advice. It means a lot to me.
Regards
Xing.

**Comment by xavierleroy** [comment]
Just for the record: I did observe the segfault with an older version of OCaml (4.07 instead of 4.09).  After doing `ulimit -s unlimited`, the segfault goes away and the test file compiles fine, although it takes a lot of time.  So, the segfault looks like a stack overflow that the OCaml 4.07 runtime system failed to catch and turn into an exception.
