### ISSUE TITLE
License question : CompCert as a library

### ISSUE THREAD

**Issue by giltho** [AbsInt/CompCert#333]
Hi,

I'm also a tiny bit lost in the license file. I've forked CompCert and built a pre-extracted version of part of the modules : https://github.com/giltho/CompCert.
The changes are minor and described in https://github.com/giltho/CompCert/tree/master/CHANGES.md

My group is using CompCert (and more precisely C->Csharpminor compiler + Memory OCaml module) for a project. Our code does not include CompCert directly, but my fork of CompCert is "imported" using the following in the esy.json:

```json
{
   "dependencies": {
      "compcert": "giltho/CompCert#commitHash"
   }
}
```
You can see it as an opam pin of a specific commit hash.

We'd like to open source our code under BSD license, is it conflicting with CompCert's license ? I think it isn't because we're not distributing your under a different license, we're just importing it. But I prefer asking just in case.

PS: I asked this question as an answer to an existing closed issue, but since it was closed I realised you probably wouldn't receive any notification about it.

**Comment by xavierleroy** [comment]
You can put any license of your choice on the code you wrote, because it is your code and you own the copyright. 

However, when you or your users combine your code with CompCert code, both your license and the CompCert license apply.  To a first approximation, the combination will be subject to CompCert's "non-commercial use" license. That is, the combination can be used freely for educational, research, or evaluation purposes, but not for commercial use.  The latter will require the purchase of a license from AbsInt Gmbh.

Some parts of CompCert are dual-licensed with a more liberal license.  If you only use those parts, the answer will be different.  Could you please list all the modules of CompCert that you use?

**Comment by giltho** [comment]
Hi, thanks for your answer !
The exhaustive list of modules I need is here: https://github.com/giltho/CompCert/tree/master/customlib + `makefile` and `configure`.
Although, when a user imports the projects at dependency resolution time, the entirety of the code is downloaded on their machine, but only this folder is built.

If I understand correctly what you are saying:
- I'm allowed to license my code under BSD
- If I produce a "release", with already compiled binaries, chances are that the license has to be under CompCert's "non-commercial use" license.
- Nobody is allowed to use the binaries that use the compcert library for commercial use (which is expected and was never intended anyway)

**Comment by giltho** [comment]
FYI, we're opensource here : https://github.com/GillianPlatform/Gillian :)
