### ISSUE TITLE
Connect constant time compcert with fiat-crypto

### ISSUE THREAD

**Issue by spitters** [AbsInt/CompCert#337]
Recording a conversation with @JasonGross and @atrieu 
Fiat-crypto generates straight line C code. It would be nice to combine it with the constant time compcert.
https://github.com/mit-plv/fiat-crypto

Jason: "The way to do this would be to either make an alternate version of CStringification that translated from our PHOAS ASTs to compcert's ASTs, or else to define a translation from CStringification.stmt to compcert ASTs.  (Note, however, that the pass from PHOAS ASTs to
CStringification.stmt is not currently verified (see https://github.com/mit-plv/fiat-crypto/issues/492), and the code we emit relies on being able to use __int128 (see https://github.com/mit-plv/fiat-crypto/issues/524 for some work in progress on eliminating this requirement) and relies on the C compiler
being able to recognize certain patterns for which it emits mulx, adc, sbb, and cmov.)"
I understand those are currently missing in compcert.

Previous request for __int128. However, I understand this issue is mostly solved in fiat-crypto by now.
 https://github.com/AbsInt/CompCert/issues/177#issuecomment-286456892

**Comment by JasonGross** [comment]
Indeed, we can now generate code without using int128, but it is not performance-competitive

**Comment by xavierleroy** [comment]
I'll record my thought here and then close this report because there will be no changes in CompCert.

Translating from the fiat-crypto AST to one of the CompCert languages and proving the correctness of the translation could be a good way to build confidence in the final code generation phases of fiat-crypto, and provide nice end-to-end guarantees.

However, this translation will have to use exclusively the standard C types supported by CompCert, i.e. 32- and 64-bit integers.  Perhaps because of a wrong initial design, adding a new type of numbers (integers or FP) to CompCert is extremely painful because it changes the value model, hence the memory model, and from there a great many files.  So I don't think CompCert will support 128-bit (or bigger) integers in the foreseeable future.

I think it would be less work overall to write and prove correct a compiler from fiat-crypto AST to, say, x86 SSE assembly code.  This is assuming that the AST is essentially straight-line computations over bit vectors: no function calls, no loops, no pointers, ...  Compiling such code to good assembly language is fairly straightforward, and the proofs could be significantly simpler than CompCert's proofs.

**Comment by JasonGross** [comment]
The hardest part of translating fiat-crypto to assembly is register spill allocation.  The second-hardest part is finding a performance-competitive instruction schedule.  Otherwise the translation to assembly is quite simple.

Our translation to bedrock2 currently has the same restriction as would be put on a translation to compcert, of not using 128-bit numbers.  Instead it uses special primitives for 64x64 -> 64x64 multiplication and conditional move (constant time `b ? t : f`), and does a very inefficient version of add-with-carry / sub-with-borrow.  If CompCert exposed these primitives, we could probably at this point write a reasonably efficient translation to CompCert similar to our translation to bedrock2.
