### ISSUE TITLE
Linking may fail when using -fno-inline with inline functions (missing symbols in object file)

### ISSUE THREAD

**Issue by sixcy** [AbsInt/CompCert#346]
Hello,

Given a source file `toto.c` : 
```c
inline void toto(){
}
```

And another source file `totocall.c` : 
```c
void toto(void);

int main(void){
  toto();
  return 0;
}
```

Issuing the following commands will result in an error while linking
```
ccomp totocall.c -c -o totocall.o
ccomp toto.c -fno-inline -c -o toto.o
ccomp toto.o totocall.o -o mybin
```

Result:
```
totocall.o: In function `main':
(.text+0xe): undefined reference to `toto'
collect2: error: ld returned 1 exit status
ccomp: error: linker command failed with exit code 1 (use -v to see invocation)
```

Indeed, the `toto` symbol is absent from the obtained object file `toto.o`

This was tested with the x86_64-linux build, but believe the bug also happens with other architectures

**Comment by bschommer** [comment]
This is not a bug, but you misunderstood the C semantics for `inline`, see ISO C99 6.7.4p6:

> Any function with internal linkage can be an inline function. For a function with external
linkage, the following restrictions apply: If a function is declared with an inline function specifier, then it shall also be defined in the same translation unit. If all of the
file scope declarations for a function in a translation unit include the inline function
specifier without extern, then the definition in that translation unit is an inline
definition. An inline definition does not provide an external definition for the function,
and does not forbid an external definition in another translation unit. An inline definition
provides an alternative to an external definition, which a translator may use to implement
any call to the function in the same translation unit. It is unspecified whether a call to the
function uses the inline definition or the external definition.

Since the definition of `toto` in toto.c is without `extern` the standard explicitly disallows that the compiler produces code for this case.

**Comment by sixcy** [comment]
Thanks for the clarification, and apologies. I thought I had provided a reproducible minimal example but not quite ; the actual example is a bit more complex :

```c
/* toto.c */

inline void toto(){
}

void f(){
  toto();
}
```

```c
/* totocall.c */

void f(void);

int main(void){
  f();
  return 0;
}

```

When running `ccomp -fno-inline toto.c -c -o toto.o`, the resulting object file does not have the definition of `toto` even though it is used by `f`

```
$ nm toto.o
0000000000000000 T f
                 U toto
```

Which then results in a failed linkage.

Using `finline` however works as intended, since `toto` is inlined into `f`.

Just to be clear, in the light of this new example: is this a bug, or still a consequence of the C semantics?

**Comment by bschommer** [comment]
This is still a consequence of the C semantics, the problem is that there is no `extern` definition of the function `toto` and in that case CompCert is not allowed to generate code for `toto` however it still can inline the function, as you noticed when using `-finline`. `gcc` as well as `clang` also reject your example.

The idea behind the C standard `inline` version without static is that the function can be defined in multiple compilation units without `extern` as long as there exists only one compilation unit that contains a declaration or definition with `extern`. Then only for that compilation unit code for the function is generated. However in all other compilation units the compiler is still allowed to inline the function definition. If you have for example a `static inline` function in some header file that is included in multiple compilation units a compiler that does not support function inlining would generated multiple copies of that function, for a function just declared `inline` the compiler would only generated the code for the function once.

**Comment by sixcy** [comment]
Alright I see. Thanks a lot for your explanations, and for your time. It looked odd to have a bench working with `finline` but failing to build with `fno-inline` - but that makes sense now.
