### ISSUE TITLE
compcert configure fails on ocaml !native arch like powerpc

### ISSUE THREAD

**Issue by didickman** [AbsInt/CompCert#359]
On OpenBSD, the native compiler does not exist for Ocaml on platforms like PowerPC. So ocamlopt (the native compiler) does not exist on this architecture, only ocamlc (the bytecode compiler).

In the CompCert configure script we have line 550 which calls ocamlopt without testing for the existence of that binary. See:
https://github.com/AbsInt/CompCert/blob/master/configure#L550

Unfortunately the Compcert build seems to fail on !native ocaml platforms as a result. I went back to my notes and indeed it looks like the last time I tried a powerpc build of compcert was in 2013, which was before this Dec 2014 commit:
https://github.com/AbsInt/CompCert/commit/20c70573181f81c99ea4e8797615dac8308a9b18#diff-e2d5a00791bce9a01f99bc6fd613a39d

I suspect non-native ocaml platforms will have been broken since (which probably means few or no people are using that setup for compcert).

Here is the last openbsd/powerpc build log of compcert for reference:
http://build-failures.rhaalovely.net/powerpc/2020-01-27/lang/compcert.log

The key line from the build logs is this one:
Testing OCaml... NOT FOUND

I'm not sure if the fix is to just switch back from ocamlopt to ocamlc to check the compcert version or there's more that's involved?

If a fix is committed, we can try to enable compcert builds on the powerful openbsd/powerpc and openbsd/aarch64 bulk build machines again. Unfortunately i can no longer build compcert on those platforms myself because my own machines are too underpowered to build all the required compcert dependencies (I think we need to build rust, clang, gcc, ruby, python, and of course ocaml all on the way to building comcpert).

**Comment by xavierleroy** [comment]
I'm of two minds here.

On the one hand, it is technically possible to detect the "ocamlc available but not ocamlopt" situation and adapt the build of CompCert to build OCaml bytecode executables instead of native-code executables.

On the other hand:
- @bschommer, @m-schmidt and I find CompCert's configure script and Makefiles complicated enough and would like to stop complicating them to please everybody.
- CompCert was designed from the beginning for the embedded systems market: it's a cross-compiler that most users will run on recent x86-64 workstations and servers. Running CompCert on "retro" hardware sur as macppc, and with the additional slowdowns caused by OCaml bytecode, will be an unpleasant experience.
- The "macppc" hardware that OpenBSD runs on is disappearing (our last PowerMac G5 at Inria died one year ago), so very few persons are running OpenBSD/PowerPC, very very few persons are using OpenBSD/PowerPC as a development platform, and very very very few persons (probably nobody) is interested in developing with CompCert on an OpenBSD/PowerPC platform.  Why bother?

**Comment by didickman** [comment]
I’ll only note that powerpc was just an example. We have the exact same problem on aarch64 which is probably considered less of a legacy platform. Defer to you how you want to handle. We will adapt either way.

**Comment by xavierleroy** [comment]
In the end, @bschommer and I agreed that we can support bytecode-only builds, even though they will be unpleasant to use.   Commit 9af2892 should fix the reported issue.  Please reopen otherwise.

**Comment by didickman** [comment]
Many thanks! Indeed this diff gets us closer. I suspect one minor tweak may be need in the Makefile for tools/ndfun and tools/modorder:

> ocamlopt -o tools/ndfun str.cmxa tools/ndfun.ml
> gmake[1]: ocamlopt: No such file or directory
> gmake[1]: *** [Makefile:193: tools/ndfun]

**Comment by xavierleroy** [comment]
> I suspect one minor tweak may be needed in the Makefile for tools/ndfun and tools/modorder

You're right, sorry about that.  Should be fixed by commit 6b854265 .

**Comment by didickman** [comment]
Just confirming that with the latest commit we can produce A CompCert package On powerpc. Thanks!

(I think on aarch64 it looks like coq might be core-dumping for some reason so we’ll need that to be fixed up first.)
