### ISSUE TITLE
Question: how to verify endianness dependent ARM C code against CompCert's specs?

### ISSUE THREAD

**Issue by MSoegtropIMC** [AbsInt/CompCert#396]
In the ARM architecture models, the endianness is a parameter - unlike on x86 where it is a definition:

(https://github.com/AbsInt/CompCert/blob/1f35599abe1b82f565a9a1b1ee03f60df362f22d/arm/Archi.v#L24)
(https://github.com/AbsInt/CompCert/blob/1f35599abe1b82f565a9a1b1ee03f60df362f22d/x86_32/Archi.v#L24)

While typically it is an advantage in verification with VST to also verify that code is endianness independent, it might happen that one wants to verify endianness dependent code.

I wonder what the recommended procedure for this is. Should one add an axiom about the endianness or is there a way to access an `Archi` file which matches a CompCert for a specific endianness?

**Comment by xavierleroy** [comment]
The ARM architecture is bi-endian, and CompCert lets you select endianness at configuration time, hence the `Parameter`.

I have sometimes wished that Coq would provide a way to instantiate a global `Parameter` with an actual definition "after the fact", but I understand that it would be hacky and hard to make sound.

For your example I would add an hypothesis `Archi.big_endian = false` to the verification of the C functions that depend on endianness. So that in the end you get a nice theorem "my code is correct if run in little-endian mode".

**Comment by xavierleroy** [comment]
I hope the question was answered.  Reopen this issue if not.

**Comment by MSoegtropIMC** [comment]
Yes, thank you! I added the endianness Hypothesis as a section parameter, and this works well.
