### ISSUE TITLE
undefined behavior in interpreter in new bitfield handling

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#418]
revision 11aaba64

```
struct S0 {
   unsigned f0 : 20;
};

int main() {
  struct S0 toto = { 10 };
}
```

```
$ ccomp -interp ub_bitfields2.c 
Stuck state: in function main, expression <loc toto> = 10
Stuck subexpression: <loc toto> = 10
ERROR: Undefined behavior
```

**Comment by xavierleroy** [comment]
This is a known limitation of the formal semantics.  For a local variable, bit-field initialization is actually an assignment, e.g. `toto.f0 = 10;` in your example, whose semantics is a read-modify-write.  Since this is a fresh stack location, the read produces `Vundef` and the assignment goes wrong.

This could be worked around by having a bit-oriented memory model (instead of the current byte-oriented model), as in [CH2O](https://robbertkrebbers.nl/research/ch2o/), but nobody really wants to do this change.
