### ISSUE TITLE
False negative of CompCert: missing undefined behavior

### ISSUE THREAD

**Issue by shao-hua-li** [AbsInt/CompCert#433]
Hi,

For the following code,  `*(&b+1)` passed the check of `ccomp -interp`, while `*(&g+1)` did not. Since both expressions triggered buffer-overflow, I was expecting CompCert to detect all of them. 

```c
struct {
  int a;
} b;
int g;
int main() {
    *(&b + 1);
    *(&g + 1);
}
```
$ccomp -interp -quiet a.c
Stuck state: in function main, expression <loc g+4>
Stuck subexpression: <loc g+4>
ERROR: Undefined behavior
$
$

**Comment by xavierleroy** [comment]
This is due to CompCert C's peculiar semantics for values of struct or union types.  CompCert supports only scalar values (numbers or pointers), so a struct  value is actually a pointer to the struct contents, not the struct contents.  Therefore, dereferencing a pointer to a struct just gives you back the pointer; no memory is accessed.  That's why `*(&b + 1)` evaluates without errors: the pointer `&b + 1` is out of bounds, but no memory loads take place, so evaluation doesn't get stuck.

You can see this in action by adding the `-trace` option.  Relevant parts:
```
Time 4: in function main, expression *(&b + 1)
--[red_var_global]-->
Time 5: in function main, expression *(&<loc b> + 1)
--[red_addrof]-->
Time 6: in function main, expression *(<ptr b> + 1)
--[red_binop]-->
Time 7: in function main, expression *<ptr b+4>
--[red_deref]-->
Time 8: in function main, expression <loc b+4>
--[red_rvalof]-->
Time 9: in function main, expression <ptr b+4>
```
Here we see that the value of `*(&b + 1)` is `<ptr b + 4>`,  i.e. the same value as `&b + 1`, and no memory access takes place in the `red_rvalof` rule.  In contrast,
```
Time 11: in function main, statement *(&g + 1);
--[step_do_1]-->
Time 12: in function main, expression *(&g + 1)
--[red_var_global]-->
Time 13: in function main, expression *(&<loc g> + 1)
--[red_addrof]-->
Time 14: in function main, expression *(<ptr g> + 1)
--[red_binop]-->
Time 15: in function main, expression *<ptr g+4>
--[red_deref]-->
Time 16: in function main, expression <loc g+4>
Stuck state: in function main, expression <loc g+4>
Stuck subexpression: <loc g+4>
ERROR: Undefined behavior
```
Here, `red_rvalof` tries to load an int from the address `<loc g+4>` and fails because the load is out of bounds.

Hope this explains your observation.  And, yes, structs as first-class values are better avoided in CompCert, since their semantics is not quite that described in the ISO C standards.

**Comment by shao-hua-li** [comment]
Thanks for your detailed explanation, it makes sense to me. For the following case, I indeed observed that overflowed struct memory had been accessed. Is it also related to the same reason?

```c
#include<stdint.h>
struct a {
  int32_t b;
  int16_t c;
} d;
int main() {
  struct a f;
  int16_t *h = &f.c;
  *(h + 1) = 0;
  return *(h+1);
}
```
```
Time 13: in function main, statement *(h + 1) = 0;
--[step_do_1]-->
Time 14: in function main, expression *(h + 1) = 0
--[red_var_local]-->
Time 15: in function main, expression *(<loc h> + 1) = 0
--[red_rvalof]-->
Time 16: in function main, expression *(<ptr f+4> + 1) = 0
--[red_binop]-->
Time 17: in function main, expression *<ptr f+6> = 0
--[red_deref]-->
Time 18: in function main, expression <loc f+6> = 0
```

**Comment by xavierleroy** [comment]
In your second example, `*(h + 1)` refers to a scalar, so memory is actually accessed.  However, the access succeeds because it fits the padding inserted at the end of the struct.  The CompCert memory model checks bounds and permissions w.r.t. top-level objects, not w.r.t. individual sub-objects.  The access `*(h + 1)` is aligned and within the bounds `0 ... sizeof(struct a) - 1` of top-level object `d`, so it succeeds.

It looks like you're trying to use the CompCert reference interpreter as a runtime validation tool for ISO C.  That's not its purpose.  You'd be better served by rv-match or Frama-C value analysis.

The purpose of CompCert's reference interpreter is to check that a program has well-defined semantics according to the CompCert C semantics, and will therefore be compiled correctly.  The CompCert C semantics defines a lot more behaviors than the ISO C semantics: that makes CompCert more useful, in that many systems code that have undefined behavior according to ISO C have defined behavior in CompCert C and will therefore be compiled correctly, guaranteed.

As a small variation on your example, consider:
```
  int16_t *h = &f.c;
  int32_t *p = (int32_t *) (h - 2);
  *p = 42;
```
This is undefined in ISO C but guaranteed to access `a.b` in CompCert C and, therefore, in the compiled code.  Similar code can be found in the Linux kernel, to recover doubly-linked list headers from pointers to the payload of list elements.  It's important that it has defined, formally-specified behavior!

Hope this answers your questions, explicit and implicit.  Now I'll close this issue report, because these are not bugs in CompCert.
