### ISSUE TITLE
possible incorrect semantics and miscompilation for enumeration in a bitfield

### ISSUE THREAD

**Issue by monniaux** [AbsInt/CompCert#472]
A reduced version of gcc test case `20030714-1.c`:

```
enum { a, c, d } typedef b;

struct {
  b h : 2;
} l;

int main() {
  l.h = d;
  switch (l.h) {
  case d:
    return 0;
  default:
    return 1;
  }
}
```

This program, compiled with gcc, returns 0. When interpreted or executed with CompCert, it returns 1.

Examination of the RTL shows that a _signed_ shift right is used to extract the bitfield, as though it were signed.

Yet the documentation states

>  Bit fields can be of enumeration type, e.g. enum e x: 2. Such bit fields are treated as unsigned if this enables all values of the enumeration to be represented exactly in the given number of bits, and as signed otherwise

**Comment by m-schmidt** [comment]
The documentation correctly describes the behaviour of CompCert before 3.10.

CompCert 3.10 moved bit field support in the verified frontend. We have to decide whether we update the manual or the implementation...

**Comment by xavierleroy** [comment]
The documentation is still the intended behavior for bitfields of enum types.  The problem here is the use of a typedef to the enum, which was not expanded like it should have been.  Commit 3845996 should fix this.  I also have a refactoring of this tricky code in C2C.ml that I'll submit as a PR shortly.
