### ISSUE TITLE
opam installation with coq-native

### ISSUE THREAD

**Issue by thery** [AbsInt/CompCert#476]
Hi, 

I am trying to install `coq-compcert` with `opam`  with  the coq native compiler (the package `coq-native` installed).
Apparently the install of `compcert` does not transfer the native code.
Is it on purpose?

**Comment by xavierleroy** [comment]
No, it's not intended.  Which generated files need installing?

**Comment by thery** [comment]
the `.coq-native` directories that are generated by the compilation when `coq-native` is installed.

**Comment by xavierleroy** [comment]
OK, this is done in e30671481 .  This commit should apply cleanly to recently-released versions of CompCert, if you feel like testing it.

**Comment by JasonGross** [comment]
Is there a plan to release 3.13 on opam so that VST will work with coq-native?

**Comment by xavierleroy** [comment]
> Is there a plan to release 3.13 on opam so that VST will work with coq-native?

In the past, @MSoegtropIMC kindly prepared the OPAM packages for CompCert, but maybe it's time for me to take over that chore.  @MSoegtropIMC : do you have plans concerning CompCert 3.13 on OPAM?

**Comment by MSoegtropIMC** [comment]
@xavierleroy : I tend to do opam package maintenance when I prepare a new Coq Platform release - which is due soon (since Coq 8.18 has been released).

In general I would prefer if you do the opam packages, because you have additional information about dependency versions. I simply but in what works. Say if I find that you need an updated version of Flocq or menhir, I wouldn't put effort into finding out which are the minimum versions which work, but put in the latest versions, with which I tested it (to be safe). You might find more relaxed conditions with your background knowledge.

Besides also information like contributor lists might change.

**Comment by xavierleroy** [comment]
All right, I just pushed some packages for CompCert 3.13, I hope they work.

**Comment by MSoegtropIMC** [comment]
@xavierleroy : in case there are CI timeout issues (VST definitely has such issues, but afair CompCert is fine) please ping me and I will do a local test.
