### ISSUE TITLE
BSD license missing

### ISSUE THREAD

**Issue by rhymoid** [AbsInt/CompCert#87]
From [the `LICENSE` file, lines 74-76](https://github.com/AbsInt/CompCert/blob/6b7b7a73f6d04517ffeb4c6faa59ea403d85925f/LICENSE#L74):

> The files contained in the runtime/ directory and its subdirectories are Copyright 2013-2014 INRIA and distributed under the terms of the BSD license, included below.

As far as I can see, only the following licenses follow: 

* INRIA Non-Commercial License Agreement for the CompCert verified compiler
* GNU General Public License, version 2
* GNU Lesser General Public License, version 3

Inclusion of this particular license is quite important, because there are at least three well-known variants of it.

**Comment by xavierleroy** [comment]
Fixed in commit [master 4afa316].  

The BSD license used was already included in the header of all the CompCert files covered by this license, but you're right that it should have been included in the LICENSE file as well.

The variant used is the 3-clause BSD, the one that OSI calls "The BSD License".
